server:
  port: 80

spring:
  devtools:
    livereload:
      enabled: false
  profiles:
    active: dev

logging:
  file: siwuxie.log
  level:
    org.springframework.web: off

siwuxie:
  cors-open: true
  swagger-open: true
